[hinting]
PPEM_MIN = 11
PPEM_MAX = 48
CANONICAL_STEM_WIDTH = [[12,90],[18,90],[26,97],[36,97],[48,97]]
CANONICAL_STEM_WIDTH_DENSE = [[12,72],[36,72],[48,72]]
ABSORPTION_LIMIT = 120
STEM_SIDE_MIN_RISE = 36
STEM_SIDE_MIN_DESCENT = 51
STEM_CENTER_MIN_RISE = 36
STEM_CENTER_MIN_DESCENT = 50
STEM_SIDE_MIN_DIST_RISE = 75
STEM_SIDE_MIN_DIST_DESCENT = 72
BOTTOM_UNIFY_FORCE = [[11,100],[36,0],[48,0]]
BOTTOM_UNIFY_FORCE_DIAG = [[11,100],[36,0],[48,0]]
TOP_UNIFY_FORCE = [[11,50],[36,0],[48,0]]
TOP_UNIFY_FORCE_DIAG = [[11,50],[36,0],[48,0]]
SLOPE_FUZZ = 0.121
SLOPE_FUZZ_NEG = 0.08
BLUEZONE_BOTTOM_CENTER = -70
BLUEZONE_BOTTOM_LIMIT = -48
BLUEZONE_TOP_CENTER = 830
RISE = [[11,15],[24,0],[36,0],[48,0]]
SINK = [[11,0],[36,0],[48,0]]
SINK_DIAGL = [[11,0],[36,0],[48,0]]
GRAVITY = [[11,0],[36,0],[48,0]]
CONCENTRATE = [[11,0],[36,0],[48,0]]
CHEBYSHEV_4 = [[11,0],[36,0],[48,0]]
CHEBYSHEV_5 = [[11,0],[36,0],[48,0]]
TOP_CUT = [[11,0],[16,0],[36,1],[48,1]]
BOTTOM_CUT = [[11,0],[36,0],[48,0]]
TOP_CUT_DIAGH = [[11,0],[36,0],[48,0]]
BOTTOM_CUT_DIAGL = [[11,0],[36,0],[48,0]]
TOP_CUT_DIAG_DIST = [[11,0],[36,1],[48,1]]
PPEM_INCREASE_GLYPH_LIMIT = 19
BLUEZONE_TOP_BAR = [[12,820],[14,825],[15,840],[16,815],[36,799]]
BLUEZONE_TOP_DOTBAR = [[12,808],[36,791]]
BLUEZONE_BOTTOM_BAR = [[12,-49],[16,-70],[36,-48]]
BLUEZONE_BOTTOM_DOTBAR = [[12,-75],[36,-60]]