[hinting]
PPEM_MIN = 11
PPEM_MAX = 48
PPEM_LOCK_BOTTOM = 20
CANONICAL_STEM_WIDTH = [[11,67],[36,67],[48,67]]
CANONICAL_STEM_WIDTH_DENSE = [[11,67],[36,67],[48,67]]
ABSORPTION_LIMIT = 120
STEM_SIDE_MIN_RISE = 36
STEM_SIDE_MIN_DESCENT = 53
STEM_CENTER_MIN_RISE = 36
STEM_CENTER_MIN_DESCENT = 50
STEM_SIDE_MIN_DIST_RISE = 75
STEM_SIDE_MIN_DIST_DESCENT = 75
BOTTOM_UNIFY_FORCE = [[11,100],[24,5],[36,0],[48,0]]
BOTTOM_UNIFY_FORCE_DIAG = [[11,50],[15,50],[16,45],[17,5],[36,0],[48,0]]
TOP_UNIFY_FORCE = [[11,50],[15,50],[16,35],[24,10],[36,0],[48,0]]
TOP_UNIFY_FORCE_DIAG = [[11,50],[15,50],[16,35],[24,10],[36,0],[48,0]]
MAX_SW_OVERFLOW_CPXS = [[11,1],[15,25],[20,50],[36,50],[48,50]]
MAX_SW_SHRINK_CPXS = [[11,25],[20,50],[36,50],[48,50]]
Y_FUZZ = 8
BLUEZONE_BOTTOM_CENTER = -70
BLUEZONE_BOTTOM_LIMIT = -45
BLUEZONE_TOP_CENTER = 835
BLUEZONE_TOP_LIMIT = 813
RISE = [[11,20],[15,20],[20,15],[26,0],[36,0],[48,0]]
SINK = [[11,8],[36,0],[48,0]]
SINK_DIAGL = [[11,0],[36,0],[48,0]]
GRAVITY = [[11,0],[36,0],[48,0]]
CONCENTRATE = [[11,0],[36,0],[48,0]]
CHEBYSHEV_4 = [[11,0],[36,0],[48,0]]
CHEBYSHEV_5 = [[11,0],[36,0],[48,0]]
TOP_CUT = [[11,0],[18,0],[19,0],[36,0],[48,0]]
BOTTOM_CUT = [[11,0],[36,0],[48,0]]